In [11]:
import pandas as pd

In [12]:
dados = pd.read_csv("data_predicted.csv")

In [13]:
dados.head()

,Unnamed: 0,ID,DATA,TITULO,EMPRESA,LOCAL,LINK,DESCRICAO,Cargo,Remoto,Resumo,Senioridade,0
0,0,pessoa-especialista-inteligencia-growth-at-bp-...,2023-10-20,PESSOA ESPECIALISTA INTELIGENCIA GROWTH,BP - A Beneficência Portuguesa de São Paulo,"São Paulo, SP",https://br.linkedin.com/jobs/view/pessoa-espec...,Excelente porque somos plurais! Cada pessoa qu...,1,0,Analista de Dados para o setor de Marketing Di...,Pleno,0.477393
1,1,cientista-de-dados-sr-at-genial-investimentos-...,2023-10-20,Cientista de Dados Sr,Genial Investimentos,"São Paulo, SP",https://br.linkedin.com/jobs/view/cientista-de...,Buscamos profissionais que tenham vontade de c...,2,0,Vaga para Cientista de Dados trabalhando com a...,Sênior,0.697244
2,2,analista-de-planejamento-pl-at-harpia-human-ca...,2023-10-20,Analista de Planejamento PL,Harpia Human Capital,"Rio de Janeiro, RJ",https://br.linkedin.com/jobs/view/analista-de-...,Estamos auxiliando um de nossos clientes do va...,0,0,Vaga de Analista de Planejamento Pleno em empr...,Pleno,0.275779
3,3,intelig%C3%AAncia-de-mercado-at-hecke-import-3...,2023-10-20,Inteligência de mercado,Hecke Import,"Curitiba, PR",https://br.linkedin.com/jobs/view/intelig%C3%A...,A HECKE IMPORT está em busca de Profissional d...,1,0,Profissional de Business Intelligence com expe...,Júnior,0.285567
4,4,consultor-de-automa%C3%A7%C3%A3o-at-v-tal-3742...,2023-10-20,Consultor de Automação,V.tal,"São Paulo, SP",https://br.linkedin.com/jobs/view/consultor-de...,Job Description\r\n\r\nSomos um time de alta p...,1,0,Vaga para Analista/Engenheiro de Dados para at...,Pleno,0.254059

In [10]:
len(dados)

47

In [16]:
dados_predicted = pd.read_csv("data_predicted.csv")

In [18]:
dados_predicted

,ID,DATA,TITULO,EMPRESA,LOCAL,LINK,DESCRICAO,0
0,cientista-de-dados-s%C3%AAnior-especialista-at...,2023-11-07,Cientista de Dados - Sênior /Especialista,Dattos,Brasil,https://br.linkedin.com/jobs/view/cientista-de...,Somos uma empresa de tecnologia em rápido cres...,0.157427
1,analista-de-projetos-remoto-at-indicium-375165...,2023-11-07,Analista de Projetos (Remoto),Indicium,"Florianópolis, SC",https://br.linkedin.com/jobs/view/analista-de-...,Quem somos\n\nNossa missão é construir vantage...,0.060688
2,profissional-cientista-de-dados-s%C3%AAnior-at...,2023-11-07,Profissional Cientista de Dados Sênior,BRQ Digital Solutions,"São Paulo, SP",https://br.linkedin.com/jobs/view/profissional...,Código: 25414\n\nSobre a BRQ Digital\nHá 30 an...,0.308431
3,cientista-de-dados-s%C3%AAnior-deep-learning-a...,2023-11-07,Cientista de Dados Sênior (Deep learning),Ambev Tech,Brasil,https://br.linkedin.com/jobs/view/cientista-de...,Seja Cientista de Dados (Deep learning) na Amb...,0.207516
4,cientista-de-dados-s%C3%AAnior-especialista-at...,2023-11-07,Cientista de Dados Sênior /Especialista,Dattos,"São Paulo, Brasil",https://br.linkedin.com/jobs/view/cientista-de...,Sobre a Dattos\nSomos uma empresa de tecnologi...,0.157427
5,machine-learning-architect-at-caylent-3727849925,2023-11-07,Machine Learning Architect,Caylent,Brasil,https://br.linkedin.com/jobs/view/machine-lear...,Caylent is a cloud native services company tha...,0.370021
6,analista-de-crm-salesforce-marketing-cloud-at-...,2023-11-07,Analista de CRM (Salesforce Marketing Cloud),B4A,"São Paulo, SP",https://br.linkedin.com/jobs/view/analista-de-...,Aqui você vai encontrar:\n\nOportunidade de ap...,0.133435
7,ai-product-manager-bootcamp-and-project-work-a...,2023-11-07,AI Product Manager: Bootcamp and Project work,Moyyn,São Paulo e Região,https://br.linkedin.com/jobs/view/ai-product-m...,"If you are a student, graduate or career chang...",0.037073
8,ai-product-manager-bootcamp-and-project-work-a...,2023-11-07,AI Product Manager: Bootcamp and Project work,Moyyn,São Paulo e Região,https://br.linkedin.com/jobs/view/ai-product-m...,"If you are a student, graduate or career chang...",0.037073

In [21]:
df = pd.read_csv("data/newly_fetched_data.csv")

In [22]:
df

,ID,DATA,TITULO,EMPRESA,LOCAL,LINK,DESCRICAO
0,cientista-de-dados-s%C3%AAnior-especialista-at...,2023-11-07,Cientista de Dados - Sênior /Especialista,Dattos,Brasil,https://br.linkedin.com/jobs/view/cientista-de...,Somos uma empresa de tecnologia em rápido cres...
1,analista-de-projetos-remoto-at-indicium-375165...,2023-11-07,Analista de Projetos (Remoto),Indicium,"Florianópolis, SC",https://br.linkedin.com/jobs/view/analista-de-...,Quem somos\n\nNossa missão é construir vantage...
2,profissional-cientista-de-dados-s%C3%AAnior-at...,2023-11-07,Profissional Cientista de Dados Sênior,BRQ Digital Solutions,"São Paulo, SP",https://br.linkedin.com/jobs/view/profissional...,Código: 25414\n\nSobre a BRQ Digital\nHá 30 an...
3,cientista-de-dados-s%C3%AAnior-deep-learning-a...,2023-11-07,Cientista de Dados Sênior (Deep learning),Ambev Tech,Brasil,https://br.linkedin.com/jobs/view/cientista-de...,Seja Cientista de Dados (Deep learning) na Amb...
4,cientista-de-dados-s%C3%AAnior-especialista-at...,2023-11-07,Cientista de Dados Sênior /Especialista,Dattos,"São Paulo, Brasil",https://br.linkedin.com/jobs/view/cientista-de...,Sobre a Dattos\nSomos uma empresa de tecnologi...
...,...,...,...,...,...,...,...
97,developer-ios-sr-at-ci-t-3760431558,2023-11-07,Developer IOS Sr,CI&T,Brasil,https://br.linkedin.com/jobs/view/developer-io...,We partner with the world’s most valuable bran...
98,senior-developer-java-brazil-at-ci-t-3741509851,2023-11-07,"Senior Developer Java, Brazil",CI&T,"Campinas, SP",https://br.linkedin.com/jobs/view/senior-devel...,We partner with the world’s most valuable bran...
99,senior-java-developer-brazil-at-ci-t-3760432298,2023-11-07,"Senior Java Developer, Brazil",CI&T,"Campinas, SP",https://br.linkedin.com/jobs/view/senior-java-...,We partner with the world’s most valuable bran...
100,pessoa-desenvolvedora-php-s%C3%AAnior-at-inter...,2023-11-07,Pessoa Desenvolvedora PHP Sênior,INTERA | Soluções de Recrutamento,"São Paulo, SP",https://br.linkedin.com/jobs/view/pessoa-desen...,Seja Desenvolvedor Backend (PHP) Sênior!\nA AI...
101,part-time-personalized-internet-ads-assessor-j...,2023-11-07,Part-Time Personalized Internet Ads Assessor -...,TELUS International AI Data Solutions,Brasil,https://br.linkedin.com/jobs/view/part-time-pe...,Our Company\nTELUS International AI-Data Solut...